### PR TITLE
Added Badge Dropdown

### PR DESCRIPTION
**Pull request by bruncbrunc**

### CODE REVIEW

**Comment by ThatSimplex** [comment]
Why don't you put [this](https://github.com/RedstonerServer/redstoner.com/pull/19/files#diff-1acd2e7e27a227829d5d14a91c863bb6R143) under the `t.integer "role_id"` line? That will make it more visible and easier to edit, and since it also is more important than the mail stuff :P

**Comment by bruncbrunc** [comment]
Good point. I'll do it when I get the chance.

**Comment by bruncbrunc** [comment]
However, when the database is created, the badge_id is put at the end, due to how the migrations work. It may make more sense to keep it as it is.

**Comment by bruncbrunc** [comment]
Yeah, if I move the badge_id in the schema, it won't match up with the migrations. I won't edit it.

**Comment by ThatSimplex** [comment]
atleast remove [this](https://github.com/RedstonerServer/redstoner.com/pull/19/files#diff-4676c008b11a5480d73d4a6de01e45b9R33) since you have removed more of the donor stuff :P since the link was wierd I am pointing towards the `def donor?` in `user.rb`

**Comment by tadhgboyle** [comment]
Just a note, when I click on a badge, i.e.: Lead, it brings me to the donator page. Couldn't you make a `/users?=lead` page?

**Comment by bruncbrunc** [comment]
Yes I will. Thank you for pointing it out

**Pull request merged**
