### PR TITLE
An Option to resend the confirmation mail

### PR DESCRIPTION
**Pull request by ThatSimplex**
You should now be able to resend the confirmation mail with the click of
a link that is next to the warning that the mail isn't confirmed.

You are free to change what it will say in the email and other stuff, but I tested it with this and it works.

### CODE REVIEW

**Comment by jomo** [comment]
Can't we just call `register_mail(@user, false)` instead of duplication everything?

**Comment by ThatSimplex** [comment]
That would work too, but I didn't think of that option.
I can change it and make a new PR if you want.

**Comment by jomo** [comment]
Just change it in this branch and squash commits

**Comment by ThatSimplex** [comment]
I don't know how to do what you just asked for, but I did what you wanted with the mailing system :P

**Pull request closed without merging**
