### PR TITLE
Added the ability to encrypt notification emails with a public key.

### PR DESCRIPTION
**Pull request by LogalDeveloper**
This pull request is intended to add the ability to encrypt notification emails with a public key. Here's what it changes:
- Adds a public key field to the notification settings page.
- Makes the mailer encrypt emails if the recipient has a public key added to their account.

### CODE REVIEW

**Comment by Dico200** [comment]
Why would someone use this?

**Comment by Minenash** [comment]
https://redstoner.com/forums/threads/5049-encrypted-emails

**Comment by Dico200** [comment]
I disagree with the addition of this feature, I think it has very little value to it. The way it's implemented on the email page also might confuse people that have no software/security background or experience, as it doesn't explain ... anything. The only thing there's to go on is "public key". It should be a bit more hidden, behind a button like "upload or change public key" with some additional information on the page or some "don't do this if you're not a nerd" disclaimer.

Next to no emails are sent unencrypted nowadays. Gmail requires SSL and in many cases TLS too (don't ask me for specifics), I can't imagine the same not applying to outlook. Redstoner doesn't share your password with you through email (obviously). What is it that you're protecting, and from whom?
What email clients support decrypting this additional layer of security anyway? Am I just uninformed? It doesn't make sense to me why this should exist. 

For the record, I'm not going to fight you for adding this feature, but I wanted to leave my opinion here for you to reconsider its value.

**Comment by LogalDeveloper** [comment]
While most of the notifications you would receive would be public knowledge since you can browse most of the forums while not logged in, it is primarily a feature meant to increase privacy. We currently send our email through Google Mail, which is not well known for being the greatest in privacy and is very distrusted by some people. I am definitely one of those people. If you decide to have your emails encrypted, then Google will only ever see ciphertext which they can't collect any information on.

Of course, this is entirely an optional feature with no enforcement being put on, so for the majority of people who will not use this feature, it will not affect them at all and they will still receive email notifications like usual.

**Comment by Minenash** [comment]
All notification emails will be encrypted with this key if you supply it.

> If you supply it.

Also clients like protonmail does the deception thing (I believe)

**Comment by LogalDeveloper** [comment]
For people who use ProtonMail, this feature is actually a great addition since all you have to do is supply your public key and you have increased your privacy without changing any experiences on our forums or on the ProtonMail client.

**Comment by Pepich** [comment]
It was requested by me due to the fact that this should be a thing everywhere. Are you 100% that every step in the chain of sending your mail happens by trusted sources on encrypted channels? You send your mail to google through an https webform or a mail client (hopefully) using a secure communication method - but you have no clue about where that mail goes, who sees it and who tampers with it. Sure you trust your email providers to not give out your mails unless law enforcement asks them to, and to use secure protocols exclusively - but it‘s still a trust based system. I don‘t like trust based systems. When there is a solution that no longer requires trusting others to do it right, which is free, easy to implement, easy to use and provides security where it was before only based on assumptions and trust - which reasons are there not to use it? From my experience it was as simple as installing the pgp plugin to my mac os mail client. No fancy client required. One simple plugin and it automatically signs and if there‘s a known key for the recipient then encrypts the mails, as well as decrypts incoming traffic. Same on my phone (even though here done through a 3rd party application) - decrypting mails is as simple as providing my touch ID. There‘s nothing hard to use to it. There‘s literally no downside to this except you having no excuse anymore when someone receives a mail from you but you claim it wasn‘t sent by you. Either it‘s signed or it isn‘t. Encrypting your mails should be made available as broadly as possible. Don‘t build trust based systems when you don‘t have to.

**Pull request merged**
