### PR TITLE
Added UTC dates option

### PR DESCRIPTION
**Pull request by bruncbrunc**

### CODE REVIEW

**Comment by ThatSimplex** [comment]
Can I just ask were the update to routes.rb are? since I can't seem to find it.

**Comment by bruncbrunc** [comment]
https://github.com/MrYummy/redstoner.com/blob/80c259cd3f5e94d2f31842e8ac3e579d061f2711/config/routes.rb

**Comment by ThatSimplex** [comment]
You shouldn't include the GemFile, GemFile.lock and databse.yml in the commits/PR. Since you need to remember that stuff that works for you might not work for where the server/website is deployed. So the files should be kept just for you :P

**Comment by ThatSimplex** [comment]
But why are the commit that is called "Updated routes.rb" called that when that is not the commit with the update to the file routes.rb?

**Comment by bruncbrunc** [comment]
(referring to gentile, etc.) Oh, I kept those in? I thought I changed them back (I usually do). I'll fix it when I get home. Thanks for checking it out.
(Referring to the commits) I didn't have time to squash the commits. I will when I get the chance.

**Comment by bruncbrunc** [comment]
*gemfile

**Comment by bruncbrunc** [comment]
Could you give me a link to the gemfile/database.yml changes?

**Comment by ThatSimplex** [comment]
Never mind it is as it is supposed to be, it was just me not actually checking how it was, but to make it easier and to avoid confusing, just don't include them in the next commits. Basically keep them "private" so that you can make changes to them so they will work for you, but not include them in the commits/PRs.

When I was working on stuff for this website on windows I found it useful to comment out the `gem unicorn` line in the gemfile or do `bundle install --without production` if I remember correctly so that you won't get errors when installing new/updating gems.

**Comment by bruncbrunc** [comment]
I never include them in my commits. I understand that they need to be altered to work on my development environment.

**Comment by ThatSimplex** [comment]
So much unneeded space filler Please change that :P

**Comment by bruncbrunc** [comment]
That occurs whenever a migration is generated. I was planning on updating it when I got home.

**Comment by bruncbrunc** [comment]
Everything is fixed as of now.

**Comment by ThatSimplex** [comment]
Just a minor issue, but please fix [this](https://github.com/RedstonerServer/redstoner.com/pull/20/commits/3f3590765d3ad5ba7286ab22963ba43f89b3eb9c#diff-c52b8a2053c82664ef5342e72953aad5R13) tab/space so it lines up with the element that starts it.

**Comment by bruncbrunc** [comment]
While attempting to fix that, I ended up adding the wrong files and deleting all of the code that I added. I'll...do it all again tomorrow, I guess.

EDIT: I found it buried in my backup files. Everything is fine. *sigh of relief*

**Pull request closed without merging**
